### ISSUE TITLE
Design the architecture and api design for the application

### ISSUE THREAD

**Issue by Nemo21** [Inderpreet02/shreddit#10]
Proper documentation of the architecture of the application is required which answers the following questions:

1. What tech stack is being used to achieve what? (Be precise and detailed)
2. Are there any other alternatives which can be used to decrease latency of the application?
3. What are the API end points for what features?
4. Reasoning of why a tech stack is used instead of something else.

**Comment by Inderpreet02** [comment]
Frontend
- React (Ui library)
- React Query (For making api requests and client side caching) 
- Mui icons (For icons can use any other) 
- Context API (For global state management if want to use redux can discuss but best will be Zustand but it's up for discussion, omg zustand looks so cute) 
- Shandcn (If you don't want to bother much with UI components this will mostly solve it , can work with any tbh mui,shadcn or if there is any new icon library trending) 
- This should cover most things if need sm else will see later

**Comment by Nemo21** [comment]
What about the backend and database connection ?

**Comment by Inderpreet02** [comment]
Backend
- Postgres (ElephantSQL as db) [This is finished as in its dead https://www.elephantsql.com/blog/end-of-life-announcement.html check this link for more]
- Redis (Inmemory cache will cache api responses and some other very interesting things that can do but initially only api) 
- Express (To make apis consider nest if can) 
- Morgan (For logs)
- Elastic (DB will use for search will do optimistic recommend on search similar to google and can further use for logging but that's not on priority) 
- TypeORM (for making sql queries not required can go with raw strings) 
- Can't remember name will add later(Sequelize dk) (Tool to prevent XSS and sql injections)

**Comment by Inderpreet02** [comment]
DevOps
- This is an open ended point for now 
- - Will make docker images
- Host on AWS or CloudFlare Or a Combination of both
